
import 'dart:convert';
import 'dart:io';

import 'package:churchIn/utils/colors.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_html/flutter_html.dart';
import 'package:flutter_svg/svg.dart';
import 'package:http/http.dart' as http;
import 'package:qr_code_scanner/qr_code_scanner.dart';

import 'helpers/encrypter.dart';
import 'helpers/helper.dart';

class PolicyPage extends StatefulWidget {
  const PolicyPage() ;

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".


  @override
  State<PolicyPage> createState() => _PolicyPageState();
}

class _PolicyPageState extends State<PolicyPage> {



  @override
  Widget build(BuildContext context) {
    final eventid = ModalRoute.of(context)!.settings.arguments as Map<String,dynamic>;
    return Scaffold(
    resizeToAvoidBottomInset: false,
    body:
    SingleChildScrollView(
    child: Container(
    child:Column(
    children: <Widget>[
    Container(
    // margin: EdgeInsets.fromLTRB(0, 0, 5,5),
    child: Row(
    mainAxisSize: MainAxisSize.max,
    mainAxisAlignment: MainAxisAlignment.spaceBetween,
    crossAxisAlignment: CrossAxisAlignment.start,
    children: <Widget>[
    //FlutterLogo(size: 100,),
    SvgPicture.asset(
    "assets/images/newlogo.svg",
    width: 50,
    height: 50,
    ),
    IconButton(
    onPressed: (){
    Navigator.pushNamed(context, "/scanner");
    },
    icon: Icon(
    Icons.home, size: 30,color: Colors.orange,
    )
    ),
    ]
    ),
    ) ,
    Html( data:     """

    <h2 class='card-title'>Privacy Policy</h2>

    <p>This is our privacy policy and it’s effective as of 22nd March 2023, any subsequent update will be communicated to both our admin users and end users via email.</p>

    <p><b>Admin Users:</b> These are organization or individuals that register with us for the purpose of generating QR codes for their members or clients. They basically use our services to collect information, register subscribers, admit for events, collect gifts etc.</p>
    <p><b>End Users:</b> scan QR codes provided by admin users to subscribe to membership, give/gift or attend events they are interested in.</p>

    <h4 style='padding-bottom: 16px;'>What our privacy Policy Covers</h4>
    <p>Welcome to Churchinapp, an app created for the purpose of helping our admin users generate QR code which they send to their members for registration, creating events, and receiving offering/gifts. The end users use the app to scan QR code sent to then by the admin users so they can sign up for membership, subscription plans, give/gift and attend sign in to events they want to be part of.  </p>
    <p>The aim of our privacy policy is to explain to all our users how we collect, use, store and protect personal and sensitive information they entrust us with in the course of using any of our services, it also explains the user’s choice about the collection and use of their information. This policy applies to both the admin and end users who use our services. If after reading our policy and you do not want us to use your information as stipulated in this policy, either in totality or in parts, then you should refrain from signing up to any of our services. </p>
    <hr style='color: #02AFF3;width: 78%;text-align: center;margin-inline-start: 162px;'><p style='color: #02AFF3;font-style: italic;width: 86%;text-align: center;padding-left: 178px;'>Summary: Welcome to Churchinapp, this is our Privacy policy and it’s set out to explain how we collect, store and use the information we collect when you scan and sign up, scan and register for any of our services. It also explains your choice regarding how we use your information.</p><hr style='color: #02AFF3;width: 78%;text-align: center;margin-inline-start: 162px;'>


    <h4 style='padding-bottom: 16px;'>Information We Collect</h4>
    <p>There are different ways through which we collect information from our users, they include but not limited to the following.</p>
    <p><b>•	Information you provide us with</b><p>
    <p>	As an admin user, when you sigh up with us to use our services, we ask for certain information from you, they are; your name, name of organization, phone number, email address, password, subscription plans and prices, members, event type, date of event, venue of events etc. </p>
    <p>As an end user, when you scan any QR code( generated by an admin user) to sign up for membership, events or to give/gift, we collect the following information from you; Your name, sex, date of birth, address, city/town, postal code, country, marital status, wedding anniversary, number of children, email, password (If possible, OTP login) occupation and phone number.</p>
    <p>We also collect information you send to us when ever you contact our support for enquiry or complaint, this enables Churchinapp to provide more satisfying services to all our users. If you do not provide the needed information requested on scanning or registration of any of our services, you may not be able to access or use our services or your experience may be incomplete and less satisfying.</p>

    <p><b>•	Information we receive from Third party application.</b><p>
    <p>	Churchinapp also collects information which you’ve granted third parties’ access to share with us, and this is to personalize usage and also gather the necessary insight we need in order to provide necessary and satisfying services to our users. </p>
    <p>When you make payment through stripe, we collect your payment details, name and the amount paid. This will enable us to provide necessary details to out admin users, so they are aware of the number of payments they’ve received and the number of active subscribers they have. We offer this information in a table form, and it can be downloaded as an Excel file by our admin user for record keeping and auditing.</p>
    <p>You can opt out at anytime if you do not want this information shared with us or adjust your privacy settings with them to prevent them from sending this information.</p>

    <h4 style='padding-bottom: 16px;'>How We use your Information</h4>
    <p>We collect information from you when you sign up for our services because they are important to us, but we owe you an explanation as to how this personal information are used. We use them for the following purposes. </p>
    <p><b>• For statistical analysis,</b> we are interested in keeping records of our subscribers, hence we use information provided by our admin users to keep track of the number of users currently using our services. The number currently active in subscription by month or years, this will help us in auditing and reporting. </p>
    <p>• Our admin users through their unique QR code collects information from their members who uses the code via their mobile scan or through any other scanning application. Their information stored at our data base are available in table format for our admin users to download as Excel document to know the number of subscribers, members, amount they’ve received or number of people who signed up for their events. Knowing this numbers help them provide more excellent service to their users and allow us to serve them and their members much better.</p>
    <p><b>• Reporting Purpose;</b> For every business like ours reporting is very important as this helps in making projections, speculation, and planning. Through reporting, other members of the team has the right information they need to provide necessities that will enhance users’ satisfaction and generally improve the quality of our services all aimed at giving you the right service that will suite your business or organization.  The admin users as well are able to use the information obtained to report to their team or organization the numbers of subscribers/members they have, amount received through giving/gifts and the number of active subscribers they have at a particular time, it helps them know how well they are doing and the peak time for their subscription thereby giving them insight on what’s working more for them.</p>

    <h4 style='padding-bottom: 16px;'>Sharing Your Information</h4>
    <p>We share your information with admin users and other third party partners for the purpose of providing them all the necessary information they might need to provide excellent services to you and also improve the quality of their services and generally improve the quality of service we provide to all our users. </p>
    <p>We might share some of your personal information with our third party service provider in order to provide  services to you or for Churchinapp business interest, some of these partners includes<br>
    o	Billing, stripe connect is most recommended. <br>
    o	Email services <br>
    o	Security<br>
    o	Hosting and storage
    </p>

    <h4 style='padding-bottom: 16px;'>Sharing with the authority</h4>
    <p>We might sometimes be required to share information with law enforcement, police, intelligence, and other agencies if we have good faith and belief that it is necessary to detect, prevent or address fraud, legal or other illegal activities to protect other users and Churchinapp, this is to aid investigation which will most likely prevent death or other bodily harm. </p>

    <h4 style='padding-bottom: 16px;'>How we store and how long we retain your information</h4>
    <p>The information we collect from you upon registration for any of our services can be stored in our data base and sometimes transferred to a destination that is outside of your city/town or even country. This information is stored in an encrypted format because we care about your privacy, and it remains inaccessible except on occasions stipulated in our policy where we must share them for the purpose of providing excellent service to our users and partners.</p>
    <p> The information stored is solely for the purpose of reporting and auditing as described in our policy. We retain your information for as long as possible with your continuous use of our services to provide and serve you with excellent services.</p>
    <p>After terminating your use of our services by deleting your account or details, we may retain your information a little longer if we believe it will be necessary for the defense of any legal claim that might come up in the future. </p>

    <h4 style='padding-bottom: 16px;'>Your Choices About Your Information</h4>
    <p>As users of Churchinapp, there are certain rights you have as regards the information you provide with us when you use our services.<br>
    o	You can access uploaded information, view, update and even delete them entirely. <br>
    o	Your can request to change your password if you feel it’s compromised to prevent another person from using your account and viewing your details. <br>
    o	You can request that we send your information to a third party or prevent such from happening.<br>
    o	You can at anytime delete your account with us and that will prevent you from further user of our services.<br>
    Remember you can make inquires to be sure of what is obtainable about your rights using the email provided in the contact us section.
    </p>

    <h4 style='padding-bottom: 16px;'>Churchinapp Children’s Policy</h4>
    <p>In this policy, children are persons who are under the age of 13 or below the minimum legal age in the child’s country of origin or residence. Our services and content are not directed at children, to this effect children are forbidden from registering by themselves for any of our services without parental consent or supervision. When signing up for children or teens the following information are all that is needed; Name, gender, teacher (optional), class group (0-12, 9-18 etc)</p>
    <p>Aside when provided by a parent or guardian, churchinapp will not knowingly collect or solicit personal information from a child without express permission from their parents or guardian. If we learn that we collected personal information from a child either through complaints or other ways, we will delete such data as quickly as possible, you can contact us via email <a style='color: #02AFF3;'>support@churchinapp.com</a> if you have any information about us collecting data from a child.</p>

    <h4 style='padding-bottom: 16px;'>Changes to This Policy</h4>
    <p>From time to time there may be need to change our privacy policy due to update in our service or  to ensure compliance with applicable laws. When this changes are posted, the “last updated” date  you see at the top of this page will be revised. If there are major changes in how we collect, use, store and share your personal information you’ve provided us with, we will notify you by sending an email to the address you provided us with when you registered for any of our services. We advice you check this page from time to time so as to stay informed on this things.</p>

    <h4 style='padding-bottom: 16px;'>Contact Us</h4>
    <p>We want to provide you with the best services you will need hence we would love to hear from you. If you have any question, suggestions or complaints regarding our privacy policy, do not hesitate to contact us by emailing us at <a style='color: #02AFF3;'>support@churchinapp.com</a></p>

"""
    ),
          ]) )));
  }
}